language: python
sudo: false
os:
  - linux
python:
  - 3.5
install:
  - pip install coveralls flake8
  - pip install .
script:
  - flake8 . --ignore=F403,E501,E123,E128 --exclude=build
  - nosetests --with-coverage --cover-package=economicsl
after_success:
  - coveralls
